"""
Generated-style gRPC service stubs for the fraud detection service.
In production, these would be auto-generated by grpc_tools.protoc from fraud.proto.
Provides the servicer base class and server registration utilities.
"""

import grpc


class FraudDetectionServiceServicer:
    """Base class for FraudDetectionService implementations."""

    def CheckTransaction(self, request, context):
        """Analyze a single transaction for fraud."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckBatchTransactions(self, request, context):
        """Analyze multiple transactions in a batch."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamTransactions(self, request_iterator, context):
        """Handle streaming transactions for real-time analysis."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelInfo(self, request, context):
        """Return metadata about the ML model."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    """Register the FraudDetectionService servicer with a gRPC server."""
    from grpc import unary_unary_rpc_method_handler
    from grpc import unary_stream_rpc_method_handler
    from grpc import stream_stream_rpc_method_handler

    rpc_method_handlers = {
        "CheckTransaction": unary_unary_rpc_method_handler(
            servicer.CheckTransaction,
        ),
        "CheckBatchTransactions": unary_unary_rpc_method_handler(
            servicer.CheckBatchTransactions,
        ),
        "StreamTransactions": stream_stream_rpc_method_handler(
            servicer.StreamTransactions,
        ),
        "GetModelInfo": unary_unary_rpc_method_handler(
            servicer.GetModelInfo,
        ),
    }

    generic_handler = grpc.method_service_handler(
        "fraud.FraudDetectionService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))


class FraudDetectionServiceStub:
    """Client stub for calling the FraudDetectionService."""

    def __init__(self, channel):
        self.CheckTransaction = channel.unary_unary(
            "/fraud.FraudDetectionService/CheckTransaction",
        )
        self.CheckBatchTransactions = channel.unary_unary(
            "/fraud.FraudDetectionService/CheckBatchTransactions",
        )
        self.StreamTransactions = channel.stream_stream(
            "/fraud.FraudDetectionService/StreamTransactions",
        )
        self.GetModelInfo = channel.unary_unary(
            "/fraud.FraudDetectionService/GetModelInfo",
        )
