"""
Generated-style protobuf message classes for the fraud detection service.
In production, these would be auto-generated by grpc_tools.protoc from fraud.proto.
"""


class Transaction:
    """Represents a financial transaction to analyze for fraud."""
    def __init__(self, transaction_id="", user_id="", amount=0.0,
                 currency="", merchant_id="", merchant_category="",
                 location="", timestamp="", card_type="",
                 ip_address="", metadata=None):
        self.transaction_id = transaction_id
        self.user_id = user_id
        self.amount = amount
        self.currency = currency
        self.merchant_id = merchant_id
        self.merchant_category = merchant_category
        self.location = location
        self.timestamp = timestamp
        self.card_type = card_type
        self.ip_address = ip_address
        self.metadata = metadata or {}


class FraudCheckResponse:
    """Contains the fraud analysis result for a transaction."""
    def __init__(self, transaction_id="", is_fraudulent=False,
                 risk_score=0.0, risk_level="", risk_factors=None,
                 recommendation="", model_version=""):
        self.transaction_id = transaction_id
        self.is_fraudulent = is_fraudulent
        self.risk_score = risk_score
        self.risk_level = risk_level
        self.risk_factors = risk_factors or []
        self.recommendation = recommendation
        self.model_version = model_version


class BatchFraudCheckRequest:
    """Batch request containing multiple transactions to analyze."""
    def __init__(self, transactions=None):
        self.transactions = transactions or []


class BatchFraudCheckResponse:
    """Batch response with fraud analysis results and summary."""
    def __init__(self, results=None, total_processed=0, flagged_count=0):
        self.results = results or []
        self.total_processed = total_processed
        self.flagged_count = flagged_count


class ModelInfoRequest:
    """Request for ML model metadata."""
    def __init__(self, model_name=""):
        self.model_name = model_name


class ModelInfoResponse:
    """Response containing ML model metadata."""
    def __init__(self, model_name="", model_version="", last_trained="",
                 accuracy=0.0, precision=0.0, recall=0.0,
                 total_predictions=0):
        self.model_name = model_name
        self.model_version = model_version
        self.last_trained = last_trained
        self.accuracy = accuracy
        self.precision = precision
        self.recall = recall
        self.total_predictions = total_predictions
