"""
Generated-style gRPC service stubs for the fraud detection service.
In production, these would be auto-generated by grpc_tools.protoc from fraud.proto.
Provides the servicer base class and server registration utilities.
"""

import grpc


class FraudDetectionServiceServicer:
    """Base class for FraudDetectionService implementations."""

    def CheckTransaction(self, request, context):
        """Analyze a single transaction for fraud."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CheckBatchTransactions(self, request, context):
        """Analyze multiple transactions in a batch."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamTransactions(self, request_iterator, context):
        """Handle streaming transactions for real-time analysis."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetModelInfo(self, request, context):
        """Return metadata about the ML model."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    """Register the FraudDetectionService servicer with a gRPC server."""
    from . import fraud_pb2

    rpc_method_handlers = {
        "CheckTransaction": grpc.unary_unary_rpc_method_handler(
            servicer.CheckTransaction,
            request_deserializer=fraud_pb2.Transaction.FromString,
            response_serializer=fraud_pb2.FraudCheckResponse.SerializeToString,
        ),
        "CheckBatchTransactions": grpc.unary_unary_rpc_method_handler(
            servicer.CheckBatchTransactions,
            request_deserializer=fraud_pb2.BatchFraudCheckRequest.FromString,
            response_serializer=fraud_pb2.BatchFraudCheckResponse.SerializeToString,
        ),
        "StreamTransactions": grpc.stream_stream_rpc_method_handler(
            servicer.StreamTransactions,
            request_deserializer=fraud_pb2.Transaction.FromString,
            response_serializer=fraud_pb2.FraudCheckResponse.SerializeToString,
        ),
        "GetModelInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetModelInfo,
            request_deserializer=fraud_pb2.ModelInfoRequest.FromString,
            response_serializer=fraud_pb2.ModelInfoResponse.SerializeToString,
        ),
    }

    # Register service using the grpc generic handler
    generic_handler = grpc.method_handlers_generic_handler(
        "fraud.FraudDetectionService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))


class FraudDetectionServiceStub:
    """Client stub for calling the FraudDetectionService."""

    def __init__(self, channel):
        self.CheckTransaction = channel.unary_unary(
            "/fraud.FraudDetectionService/CheckTransaction",
        )
        self.CheckBatchTransactions = channel.unary_unary(
            "/fraud.FraudDetectionService/CheckBatchTransactions",
        )
        self.StreamTransactions = channel.stream_stream(
            "/fraud.FraudDetectionService/StreamTransactions",
        )
        self.GetModelInfo = channel.unary_unary(
            "/fraud.FraudDetectionService/GetModelInfo",
        )
