// Code generated by protoc-gen-go. DO NOT EDIT.
// This file provides the Go structs and interfaces generated from logging.proto.
// In a real project, this would be auto-generated using protoc with the Go plugin.

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// LogEntry represents a single structured log message
type LogEntry struct {
	ServiceName string            `json:"service_name"`
	Level       string            `json:"level"`
	Message     string            `json:"message"`
	Timestamp   string            `json:"timestamp"`
	Metadata    map[string]string `json:"metadata"`
	TraceId     string            `json:"trace_id"`
}

// MetricEntry represents a single metric data point
type MetricEntry struct {
	ServiceName string            `json:"service_name"`
	MetricName  string            `json:"metric_name"`
	Value       float64           `json:"value"`
	MetricType  string            `json:"metric_type"`
	Timestamp   string            `json:"timestamp"`
	Labels      map[string]string `json:"labels"`
}

// LogResponse acknowledges receipt of log entries
type LogResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

// MetricResponse acknowledges receipt of metric entries
type MetricResponse struct {
	Success         bool  `json:"success"`
	MetricsReceived int32 `json:"metrics_received"`
}

// BatchLogRequest allows sending multiple log entries at once
type BatchLogRequest struct {
	Entries []*LogEntry `json:"entries"`
}

// BatchMetricRequest allows sending multiple metric entries at once
type BatchMetricRequest struct {
	Entries []*MetricEntry `json:"entries"`
}

// QueryLogsRequest for retrieving historical logs
type QueryLogsRequest struct {
	ServiceName string `json:"service_name"`
	Level       string `json:"level"`
	StartTime   string `json:"start_time"`
	EndTime     string `json:"end_time"`
	Limit       int32  `json:"limit"`
}

// QueryLogsResponse returns matching log entries
type QueryLogsResponse struct {
	Entries    []*LogEntry `json:"entries"`
	TotalCount int32       `json:"total_count"`
}

// LoggingServiceClient is the client API for LoggingService
type LoggingServiceClient interface {
	SendLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error)
	SendBatchLogs(ctx context.Context, in *BatchLogRequest, opts ...grpc.CallOption) (*LogResponse, error)
	SendMetric(ctx context.Context, in *MetricEntry, opts ...grpc.CallOption) (*MetricResponse, error)
	SendBatchMetrics(ctx context.Context, in *BatchMetricRequest, opts ...grpc.CallOption) (*MetricResponse, error)
	StreamLogs(ctx context.Context, opts ...grpc.CallOption) (LoggingService_StreamLogsClient, error)
	QueryLogs(ctx context.Context, in *QueryLogsRequest, opts ...grpc.CallOption) (*QueryLogsResponse, error)
}

type loggingServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewLoggingServiceClient creates a new client for the LoggingService
func NewLoggingServiceClient(cc grpc.ClientConnInterface) LoggingServiceClient {
	return &loggingServiceClient{cc}
}

func (c *loggingServiceClient) SendLog(ctx context.Context, in *LogEntry, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/logging.LoggingService/SendLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingServiceClient) SendBatchLogs(ctx context.Context, in *BatchLogRequest, opts ...grpc.CallOption) (*LogResponse, error) {
	out := new(LogResponse)
	err := c.cc.Invoke(ctx, "/logging.LoggingService/SendBatchLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingServiceClient) SendMetric(ctx context.Context, in *MetricEntry, opts ...grpc.CallOption) (*MetricResponse, error) {
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, "/logging.LoggingService/SendMetric", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingServiceClient) SendBatchMetrics(ctx context.Context, in *BatchMetricRequest, opts ...grpc.CallOption) (*MetricResponse, error) {
	out := new(MetricResponse)
	err := c.cc.Invoke(ctx, "/logging.LoggingService/SendBatchMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggingService_StreamLogsClient is the client-side streaming interface
type LoggingService_StreamLogsClient interface {
	Send(*LogEntry) error
	CloseAndRecv() (*LogResponse, error)
	grpc.ClientStream
}

type loggingServiceStreamLogsClient struct {
	grpc.ClientStream
}

func (x *loggingServiceStreamLogsClient) Send(m *LogEntry) error {
	return x.ClientStream.SendMsg(m)
}

func (x *loggingServiceStreamLogsClient) CloseAndRecv() (*LogResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingServiceClient) StreamLogs(ctx context.Context, opts ...grpc.CallOption) (LoggingService_StreamLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &grpc.StreamDesc{
		StreamName:    "StreamLogs",
		ClientStreams: true,
	}, "/logging.LoggingService/StreamLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingServiceStreamLogsClient{stream}
	return x, nil
}

func (c *loggingServiceClient) QueryLogs(ctx context.Context, in *QueryLogsRequest, opts ...grpc.CallOption) (*QueryLogsResponse, error) {
	out := new(QueryLogsResponse)
	err := c.cc.Invoke(ctx, "/logging.LoggingService/QueryLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoggingServiceServer is the server API for LoggingService
type LoggingServiceServer interface {
	SendLog(context.Context, *LogEntry) (*LogResponse, error)
	SendBatchLogs(context.Context, *BatchLogRequest) (*LogResponse, error)
	SendMetric(context.Context, *MetricEntry) (*MetricResponse, error)
	SendBatchMetrics(context.Context, *BatchMetricRequest) (*MetricResponse, error)
	StreamLogs(LoggingService_StreamLogsServer) error
	QueryLogs(context.Context, *QueryLogsRequest) (*QueryLogsResponse, error)
}

// UnimplementedLoggingServiceServer provides default implementations
type UnimplementedLoggingServiceServer struct{}

func (UnimplementedLoggingServiceServer) SendLog(context.Context, *LogEntry) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendLog not implemented")
}
func (UnimplementedLoggingServiceServer) SendBatchLogs(context.Context, *BatchLogRequest) (*LogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBatchLogs not implemented")
}
func (UnimplementedLoggingServiceServer) SendMetric(context.Context, *MetricEntry) (*MetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMetric not implemented")
}
func (UnimplementedLoggingServiceServer) SendBatchMetrics(context.Context, *BatchMetricRequest) (*MetricResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendBatchMetrics not implemented")
}
func (UnimplementedLoggingServiceServer) StreamLogs(LoggingService_StreamLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLogs not implemented")
}
func (UnimplementedLoggingServiceServer) QueryLogs(context.Context, *QueryLogsRequest) (*QueryLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLogs not implemented")
}

// UnsafeLoggingServiceServer for forward compatibility
type UnsafeLoggingServiceServer interface {
	mustEmbedUnimplementedLoggingServiceServer()
}

// LoggingService_StreamLogsServer is the server-side streaming interface
type LoggingService_StreamLogsServer interface {
	SendAndClose(*LogResponse) error
	Recv() (*LogEntry, error)
	grpc.ServerStream
}

type loggingServiceStreamLogsServer struct {
	grpc.ServerStream
}

func (x *loggingServiceStreamLogsServer) SendAndClose(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *loggingServiceStreamLogsServer) Recv() (*LogEntry, error) {
	m := new(LogEntry)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RegisterLoggingServiceServer registers the server implementation
func RegisterLoggingServiceServer(s grpc.ServiceRegistrar, srv LoggingServiceServer) {
	s.RegisterService(&LoggingService_ServiceDesc, srv)
}

// Handler functions for gRPC method dispatch
func _LoggingService_SendLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).SendLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.LoggingService/SendLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).SendLog(ctx, req.(*LogEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingService_SendBatchLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).SendBatchLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.LoggingService/SendBatchLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).SendBatchLogs(ctx, req.(*BatchLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingService_SendMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).SendMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.LoggingService/SendMetric",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).SendMetric(ctx, req.(*MetricEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingService_SendBatchMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMetricRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).SendBatchMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.LoggingService/SendBatchMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).SendBatchMetrics(ctx, req.(*BatchMetricRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingService_StreamLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LoggingServiceServer).StreamLogs(&loggingServiceStreamLogsServer{stream})
}

func _LoggingService_QueryLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).QueryLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logging.LoggingService/QueryLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).QueryLogs(ctx, req.(*QueryLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LoggingService_ServiceDesc is the service descriptor for the LoggingService
var LoggingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logging.LoggingService",
	HandlerType: (*LoggingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "SendLog", Handler: _LoggingService_SendLog_Handler},
		{MethodName: "SendBatchLogs", Handler: _LoggingService_SendBatchLogs_Handler},
		{MethodName: "SendMetric", Handler: _LoggingService_SendMetric_Handler},
		{MethodName: "SendBatchMetrics", Handler: _LoggingService_SendBatchMetrics_Handler},
		{MethodName: "QueryLogs", Handler: _LoggingService_QueryLogs_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "StreamLogs", Handler: _LoggingService_StreamLogs_Handler, ClientStreams: true},
	},
	Metadata: "logging.proto",
}
